blank_issues_enabled: false
contact_links:
  - name: Project Vyre Discord
    url: https://discord.gg/UF8yMZEmmc
    about: Our Discord server if you don't want to use GitHub Discussions.
  - name: GitHub Discussions
    url: https://github.com/Project-Vyre/Finality-Genesis/discussions
    about: Don't want to use Discord? Discuss here instead.
