#The maximum amount of items a sandwich can contain
#Range: > 2
maximum_sandwich_height = 32
#Whether randomly generated sandwiches should be added to chests in villages and some other locations
generate_chest_loot = true

