
#General settings
[general]
	#The CurseForge project ID for the modpack
	#Range: > 0
	modpackProjectID = 866410
	#The name of the modpack
	modpackName = "Finality Genesis"
	#The version of the modpack
	modpackVersion = "0.1.4b"
	#Use the metadata.json to determine the modpack version
	#ONLY ENABLE THIS IF YOU KNOW WHAT YOU ARE DOING
	useMetadata = false

