
[Camera]
	#Spyglass will function like a superzoom lens instead of a teleconverter, allowing for a full range of focal lengths (18-200).
	#Using it as a teleconverter allows only 55-200
	SpyglassSuperzoom = false

[Lightroom]
	#Time in ticks to print black and white photograph.
	#Range: > 1
	BlackAndWhitePrintTime = 80
	#Time in ticks to print color photograph.
	#Range: > 1
	ColorPrintTime = 200
	#Amount of experience awarded per printed Photograph. Set to 0 to disable.
	#Range: 0 ~ 32767
	ExperiencePerPrint = 4

