/**
 * @file Handles shape item generation.
 * 
 */

/**
 * Work in progress replacement.
 * for (const [shape, displayName] of Object.entries(global.SHAPES)) {
 *     for (const [color, colorName] of Object.entries(global.RGBWCMY)) {
 *     }
 * }
 */
global.SHAPES = {
  circle: 'Circle',
  rectangle: 'Rectangle',
  windmill: 'Windmill',
  star: 'Star'
}
let ROTATION = {
  tl: 'Top Left',
  tr: 'Top Right',
  bl: 'Bottom Left',
  br: 'Bottom Right'
}
global.RGBWCMY = {
  uncolored: '§7Uncolored',
  red: '§cColor Red',
  green: '§aColor Green',
  blue: '§9Color Blue',
  white: '§lColor White',
  cyan: '§bColor Cyan',
  magenta: '§dColor Magenta',
  yellow: '§eColor Yellow'
}
StartupEvents.registry('item', event => {
  /**
   * 
   * @param {string} itemId 
   * @param {string} displayName 
   * @param {string} texturePath 
   */
  function fireResistantShape(itemId, displayName, texturePath) {
    event.create(`kubejs:${itemId}`).displayName(displayName).texture(`kubejs:item/${texturePath}`).maxStackSize(64).fireResistant(true)
  }
  /**
   * 
   * @param {string} itemId 
   * @param {string} displayNameString 
   * @param {string} texturePath 
   */
  let shapeItemGeneration = (itemId, displayNameString, texturePath) => {
    event
      .create(`kubejs:${itemId}`)
      .displayName(`${displayNameString}`)
      .texture(`kubejs:item/shapes/${texturePath}`)
      .maxStackSize(64)
      .fireResistant(true)
  }
  for (let [shape, name] of Object.entries(global.SHAPES)) {
    event.create(`kubejs:uncolored_${shape}`)
      .formattedDisplayName(Component.string(`Uncolored ${name}`).gray().bold())
      .texture('layer0', 'kubejs:item/shape_tint')
      .color(0, 0xAAAAAA)
      .parentModel(`kubejs:item/${shape}`)
      .tag('create:upright_on_belt')
      .fireResistant(true)
    event.create(`kubejs:uncolored_left_half_${shape}`)
      .formattedDisplayName(Component.string(`Uncolored Left Half ${name}`).gray())
      .texture('layer0', 'kubejs:item/shape_tint')
      .color(0, 0xAAAAAA)
      .parentModel(`kubejs:item/left_half_${shape}`)
      .tag('create:upright_on_belt')
      .fireResistant(true)
    event.create(`kubejs:uncolored_right_half_${shape}`)
      .formattedDisplayName(Component.string(`Uncolored Right Half ${name}`).gray())
      .texture('layer0', 'kubejs:item/shape_tint')
      .color(0, 0xAAAAAA)
      .parentModel(`kubejs:item/right_half_${shape}`)
      .tag('create:upright_on_belt')
      .fireResistant(true)
    event.create(`kubejs:uncolored_${shape}_corner`)
      .formattedDisplayName(Component.string(`Uncolored ${name} Corner`).gray())
      .texture('layer0', 'kubejs:item/shape_tint')
      .color(0, 0xAAAAAA)
      .parentModel(`kubejs:item/${shape}_corner`)
      .tag('create:upright_on_belt')
      .fireResistant(true)
    // red
    event.create(`kubejs:red_${shape}`)
      .formattedDisplayName(Component.string(`Red ${name}`).red().bold())
      .texture('layer0', 'kubejs:item/shape_tint')
      .color(0, 0xFF0000)
      .parentModel(`kubejs:item/${shape}`)
      .tag('create:upright_on_belt')
      .fireResistant(true)
    event.create(`kubejs:red_left_half_${shape}`)
      .formattedDisplayName(Component.string(`Red Left Half ${name}`).red())
      .texture('layer0', 'kubejs:item/shape_tint')
      .color(0, 0xFF0000)
      .parentModel(`kubejs:item/left_half_${shape}`)
      .tag('create:upright_on_belt')
      .fireResistant(true)
    event.create(`kubejs:red_right_half_${shape}`)
      .formattedDisplayName(Component.string(`Red Right Half ${name}`).red())
      .texture('layer0', 'kubejs:item/shape_tint')
      .color(0, 0xFF0000)
      .parentModel(`kubejs:item/right_half_${shape}`)
      .tag('create:upright_on_belt')
      .fireResistant(true)
    event.create(`kubejs:red_${shape}_corner`)
      .formattedDisplayName(Component.string(`Red ${name} Corner`).red())
      .texture('layer0', 'kubejs:item/shape_tint')
      .color(0, 0xFF0000)
      .parentModel(`kubejs:item/${shape}_corner`)
      .tag('create:upright_on_belt')
      .fireResistant(true)
    // green
    event.create(`kubejs:green_${shape}`)
      .formattedDisplayName(Component.string(`Green ${name}`).green().bold())
      .texture('layer0', 'kubejs:item/shape_tint')
      .color(0, 0x00FF00)
      .parentModel(`kubejs:item/${shape}`)
      .tag('create:upright_on_belt')
      .fireResistant(true)
    event.create(`kubejs:green_left_half_${shape}`)
      .formattedDisplayName(Component.string(`Green Left Half ${name}`).green())
      .texture('layer0', 'kubejs:item/shape_tint')
      .color(0, 0x00FF00)
      .parentModel(`kubejs:item/left_half_${shape}`)
      .tag('create:upright_on_belt')
      .fireResistant(true)
    event.create(`kubejs:green_right_half_${shape}`)
      .formattedDisplayName(Component.string(`Green Right Half ${name}`).green())
      .texture('layer0', 'kubejs:item/shape_tint')
      .color(0, 0x00FF00)
      .parentModel(`kubejs:item/right_half_${shape}`)
      .tag('create:upright_on_belt')
      .fireResistant(true)
    event.create(`kubejs:green_${shape}_corner`)
      .formattedDisplayName(Component.string(`Green ${name} Corner`).green())
      .texture('layer0', 'kubejs:item/shape_tint')
      .color(0, 0x00FF00)
      .parentModel(`kubejs:item/${shape}_corner`)
      .tag('create:upright_on_belt')
      .fireResistant(true)
    // blue
    event.create(`kubejs:blue_${shape}`)
      .formattedDisplayName(Component.string(`Blue ${name}`).blue().bold())
      .texture('layer0', 'kubejs:item/shape_tint')
      .color(0, 0x0000FF)
      .parentModel(`kubejs:item/${shape}`)
      .tag('create:upright_on_belt')
      .fireResistant(true)
    event.create(`kubejs:blue_left_half_${shape}`)
      .formattedDisplayName(Component.string(`Blue Left Half ${name}`).blue())
      .texture('layer0', 'kubejs:item/shape_tint')
      .color(0, 0x0000FF)
      .parentModel(`kubejs:item/left_half_${shape}`)
      .tag('create:upright_on_belt')
      .fireResistant(true)
    event.create(`kubejs:blue_right_half_${shape}`)
      .formattedDisplayName(Component.string(`Blue Right Half ${name}`).blue())
      .texture('layer0', 'kubejs:item/shape_tint')
      .color(0, 0x0000FF)
      .parentModel(`kubejs:item/right_half_${shape}`)
      .tag('create:upright_on_belt')
      .fireResistant(true)
    event.create(`kubejs:blue_${shape}_corner`)
      .formattedDisplayName(Component.string(`Blue ${name} Corner`).blue())
      .texture('layer0', 'kubejs:item/shape_tint')
      .color(0, 0x0000FF)
      .parentModel(`kubejs:item/${shape}_corner`)
      .tag('create:upright_on_belt')
      .fireResistant(true)
    // cyan
    event.create(`kubejs:cyan_${shape}`)
      .formattedDisplayName(Component.string(`Cyan ${name}`).aqua().bold())
      .texture('layer0', 'kubejs:item/shape_tint')
      .color(0, 0x00FFFF)
      .parentModel(`kubejs:item/${shape}`)
      .tag('create:upright_on_belt')
      .fireResistant(true)
    event.create(`kubejs:cyan_left_half_${shape}`)
      .formattedDisplayName(Component.string(`Cyan Left Half ${name}`).aqua())
      .texture('layer0', 'kubejs:item/shape_tint')
      .color(0, 0x00FFFF)
      .parentModel(`kubejs:item/left_half_${shape}`)
      .tag('create:upright_on_belt')
      .fireResistant(true)
    event.create(`kubejs:cyan_right_half_${shape}`)
      .formattedDisplayName(Component.string(`Cyan Right Half ${name}`).aqua())
      .texture('layer0', 'kubejs:item/shape_tint')
      .color(0, 0x00FFFF)
      .parentModel(`kubejs:item/right_half_${shape}`)
      .tag('create:upright_on_belt')
      .fireResistant(true)
    event.create(`kubejs:cyan_${shape}_corner`)
      .formattedDisplayName(Component.string(`Cyan ${name} Corner`).aqua())
      .texture('layer0', 'kubejs:item/shape_tint')
      .color(0, 0x00FFFF)
      .parentModel(`kubejs:item/${shape}_corner`)
      .tag('create:upright_on_belt')
      .fireResistant(true)
    // magenta
    event.create(`kubejs:magenta_${shape}`)
      .formattedDisplayName(Component.string(`Magenta ${name}`).lightPurple().bold())
      .texture('layer0', 'kubejs:item/shape_tint')
      .color(0, 0xFF00FF)
      .parentModel(`kubejs:item/${shape}`)
      .tag('create:upright_on_belt')
      .fireResistant(true)
    event.create(`kubejs:magenta_left_half_${shape}`)
      .formattedDisplayName(Component.string(`Magenta Left Half ${name}`).lightPurple())
      .texture('layer0', 'kubejs:item/shape_tint')
      .color(0, 0xFF00FF)
      .parentModel(`kubejs:item/left_half_${shape}`)
      .tag('create:upright_on_belt')
      .fireResistant(true)
    event.create(`kubejs:magenta_right_half_${shape}`)
      .formattedDisplayName(Component.string(`Magenta Right Half ${name}`).lightPurple())
      .texture('layer0', 'kubejs:item/shape_tint')
      .color(0, 0xFF00FF)
      .parentModel(`kubejs:item/right_half_${shape}`)
      .tag('create:upright_on_belt')
      .fireResistant(true)
    event.create(`kubejs:magenta_${shape}_corner`)
      .formattedDisplayName(Component.string(`Magenta ${name} Corner`).lightPurple())
      .texture('layer0', 'kubejs:item/shape_tint')
      .color(0, 0xFF00FF)
      .parentModel(`kubejs:item/${shape}_corner`)
      .tag('create:upright_on_belt')
      .fireResistant(true)
    // yellow
    event.create(`kubejs:yellow_${shape}`)
      .formattedDisplayName(Component.string(`Yellow ${name}`).yellow().bold())
      .texture('layer0', 'kubejs:item/shape_tint')
      .color(0, 0xFFFF00)
      .parentModel(`kubejs:item/${shape}`)
      .tag('create:upright_on_belt')
      .fireResistant(true)
    event.create(`kubejs:yellow_left_half_${shape}`)
      .formattedDisplayName(Component.string(`Yellow Left Half ${name}`).yellow())
      .texture('layer0', 'kubejs:item/shape_tint')
      .color(0, 0xFFFF00)
      .parentModel(`kubejs:item/left_half_${shape}`)
      .tag('create:upright_on_belt')
      .fireResistant(true)
    event.create(`kubejs:yellow_right_half_${shape}`)
      .formattedDisplayName(Component.string(`Yellow Right Half ${name}`).yellow())
      .texture('layer0', 'kubejs:item/shape_tint')
      .color(0, 0xFFFF00)
      .parentModel(`kubejs:item/right_half_${shape}`)
      .tag('create:upright_on_belt')
      .fireResistant(true)
    event.create(`kubejs:yellow_${shape}_corner`)
      .formattedDisplayName(Component.string(`Yellow ${name} Corner`).yellow())
      .texture('layer0', 'kubejs:item/shape_tint')
      .color(0, 0xFFFF00)
      .parentModel(`kubejs:item/${shape}_corner`)
      .tag('create:upright_on_belt')
      .fireResistant(true)
    // white
    event.create(`kubejs:white_${shape}`)
      .formattedDisplayName(Component.string(`White ${name}`).white().bold())
      .texture('layer0', 'kubejs:item/shape_tint')
      .color(0, 0xFFFFFF)
      .parentModel(`kubejs:item/${shape}`)
      .tag('create:upright_on_belt')
      .fireResistant(true)
    event.create(`kubejs:white_left_half_${shape}`)
      .formattedDisplayName(Component.string(`White Left Half ${name}`).white().bold())
      .texture('layer0', 'kubejs:item/shape_tint')
      .color(0, 0xFFFFFF)
      .parentModel(`kubejs:item/left_half_${shape}`)
      .tag('create:upright_on_belt')
      .fireResistant(true)
    event.create(`kubejs:white_right_half_${shape}`)
      .formattedDisplayName(Component.string(`White Right Half ${name}`).white().bold())
      .texture('layer0', 'kubejs:item/shape_tint')
      .color(0, 0xFFFFFF)
      .parentModel(`kubejs:item/right_half_${shape}`)
      .tag('create:upright_on_belt')
      .fireResistant(true)
    event.create(`kubejs:white_${shape}_corner`)
      .formattedDisplayName(Component.string(`White ${name} Corner`).white().bold())
      .texture('layer0', 'kubejs:item/shape_tint')
      .color(0, 0xFFFFFF)
      .parentModel(`kubejs:item/${shape}_corner`)
      .tag('create:upright_on_belt')
      .fireResistant(true)
  }
  event.create('kubejs:blueprint_shape_base')
    .formattedDisplayName(Component.string('Blueprint Shape Base').blue())
    .texture('kubejs:item/shapes/blueprint_shape_base')
    .fireResistant(true)
  event.create('kubejs:blueprint_shape')
    .formattedDisplayName(Component.string('Blueprint Shape').blue())
    .texture('kubejs:item/shapes/blueprint_shape')
    .fireResistant(true)
  event.create('kubejs:cpu_foundation')
    .formattedDisplayName(Component.string('CPU Shape Foundation').green())
    .texture('kubejs:item/shapes/cpu_foundation')
    .fireResistant(true)
  event.create('kubejs:cpu_substrate_shape')
    .formattedDisplayName(Component.string('CPU Substrate Shape').green())
    .texture('kubejs:item/shapes/cpu_substrate_shape')
    .fireResistant(true)
  event.create('kubejs:cpu_shape')
    .formattedDisplayName(Component.string('CPU Shape').green())
    .texture('kubejs:item/shapes/cpu_shape')
    .fireResistant(true)
  event.create('kubejs:emitter_shape_base')
    .formattedDisplayName(Component.string('Emitter Shape Base').lightPurple())
    .texture('kubejs:item/shapes/emitter_shape_base')
  event.create('kubejs:emitter_shape')
    .formattedDisplayName(Component.string('Emitter Shape').lightPurple())
    .texture('kubejs:item/shapes/emitter_shape')
  event.create('kubejs:star_of_light_shape')
    .formattedDisplayName(Component.string('Star of Light Shape').yellow())
    .texture('kubejs:item/shapes/star_of_light_shape')
    .fireResistant(true)
  event.create('kubejs:watermelon_shape')
    .formattedDisplayName(Component.string('Watermelon Shape').red())
    .texture('kubejs:item/shapes/watermelon')
    .fireResistant(true)
})