
[general]

	[general.general]
		timestamps_format = 0
		streamer_mode = false
		modcore_warning = true
		essential_gui_scale = 0

	[general.online_status]
		show_essential_indicator_on_tab = true
		show_essential_indicator_on_nametags = true

	[general.experience]
		closer_placement_of_minimal_essential_menu = true
		essential_menu_layout = 0
		enable_essential = true
		quick_action_bar = true
		use_vanilla_button_texture = false
		darken_re-textured_menu_buttons = false

[hidden]
	previously_launched_with_container = 1

	[hidden.hidden]
		emote_perspective = 1
		screenshotbrowseritemsperrow = 3
		spspinnedgamerules = ""
		coinsselectedcurrency = "USD"
		coinspurchasecreatorcode = "__default__"
		showemotepagekeybindbanner = true

[emotes]

	[emotes.general]
		disable_emotes = false
		play_emotes_in_third_person_view = true
		emotes_preview = false
		emote_preview = false

[privacy]

	[privacy.general]
		display_current_server = false
		friend_privacy_settings = 0

[notifications]

	[notifications.general]
		disable_all_notifications = false
		host_world_ip_warning = true
		screeenshot_toast_duration = 1
		update_notifications = true
		screenshot_toast_duration = 1
		message_sound = true
		online_friend_alert = true
		message_notifications = true
		group_message_notifications = true

	[notifications.warnings]
		link_opening_warning = true

[quality_of_life]

	[quality_of_life.general]
		auto_refresh_session = true

	[quality_of_life.accessibility]
		enlarge_chat_metadata = false

	[quality_of_life.discord_integration]
		show_username_and_avatar = false
		set_activity_status_on_discord = false
		allow_ask_to_join = false
		show_current_server = false

	[quality_of_life.zoom]
		smooth_zoom_animation = true
		toggle_to_zoom = false
		smooth_camera_when_zoomed = true

	[quality_of_life.screenshots]
		vanilla_screenshot_message = false
		essential_screenshots = true
		screenshot_sounds = true
		"screenshot_quick_action_#1_-_top_left" = 5
		"screenshot_quick_action_#2_-_top_right" = 2
		"screenshot_quick_action_#3_-_bottom_left" = 1
		"screenshot_quick_action_#4_-_bottom_right" = 4
		post_screenshot_action = 0

[cosmetics]

	[cosmetics.general]
		hide_cosmetics_on_server_skins = false
		disable_cosmetics = false
		disable_cosmetics_in_inventory = false
		"cosmetic_&_armor_conflict_-_on_myself" = 0
		"cosmetic_&_armor_conflict_-_on_others" = 0

[__meta]
	version = 11

	[__meta.migration_log]

		[__meta.migration_log.0]

			[__meta.migration_log.0.changed]
				"general.general.gui_scale" = true

		[__meta.migration_log.1]

			[__meta.migration_log.1.changed]
				"cosmetics.general.cosmetic_armor_handling" = 0

		[__meta.migration_log.3]

			[__meta.migration_log.3.changed]
				"hidden.hidden.wardrobesortoptionmigration" = true
				"hidden.hidden.wardrobesortoption" = 1

		[__meta.migration_log.4]

			[__meta.migration_log.4.changed]
				"general.experience.show_menus" = true

		[__meta.migration_log.5]

			[__meta.migration_log.5.changed]
				"general.experience.essential_full" = true
				"cosmetics.general.show_my_cosmetics" = true
				"cosmetics.general.show_my_armor" = 0
				"cosmetics.general.show_other_players'_armor" = 0

		[__meta.migration_log.6]

			[__meta.migration_log.6.changed]
				"general.experience.automatic_updates" = true

		[__meta.migration_log.7]

			[__meta.migration_log.7.changed]
				"cosmetics.general.hide_your_cosmetics" = false

		[__meta.migration_log.9]

			[__meta.migration_log.9.changed]
				"general.general.prompt_when_visiting_trusted_hosts" = false

		[__meta.migration_log.10]
			added = ["emotes.general.emotes_preview"]

			[__meta.migration_log.10.changed]
				"emotes.general.emote_preview_in_first_person" = true

